In [1]:
!pip install transformers datasets accelerate scikit-learn torch pandas numpy -q

In [2]:
import pandas as pd
import numpy as np
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    TrainingArguments, Trainer, EarlyStoppingCallback
)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import torch
import json
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

BASE_MODEL = 'distilbert-base-uncased'
MAX_LENGTH = 256
BATCH_SIZE = 16
LEARNING_RATE = 2e-5
NUM_EPOCHS = 3
TASK = 'regression'
OUTPUT_DIR = "/content/models_foundation"

print(f"Model: {BASE_MODEL}, Device: {'GPU' if torch.cuda.is_available() else 'CPU'}")

Model: distilbert-base-uncased, Device: GPU

In [3]:
ds = load_dataset("benxh/tiktok-hooks-finetune")
df = ds['train'].to_pandas()

df['engagement_rate'] = (df['likes'] + df['comments'] + df['shares']) / (df['views'] + 1)
df['virality_score'] = df['engagement_rate'] * np.log1p(df['views'])
df['text_input'] = df['text_hook'].astype(str) + " [SEP] " + df['caption'].astype(str)
df = df.dropna(subset=['text_input', 'virality_score'])

df['uploaded_at'] = pd.to_datetime(df['uploaded_at'])
df = df.sort_values('uploaded_at')

train_size = int(len(df) * 0.70)
val_size = int(len(df) * 0.15)

train_df = df.iloc[:train_size].copy()
val_df = df.iloc[train_size:train_size+val_size].copy()
test_df = df.iloc[train_size+val_size:].copy()

print(f"Train: {len(train_df):,}, Val: {len(val_df):,}, Test: {len(test_df):,}")

README.md:   0%|          | 0.00/650 [00:00<?, ?B/s]

sharegpt_conversations.parquet:   0%|          | 0.00/36.2M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/46605 [00:00<?, ? examples/s]

Train: 32,623, Val: 6,990, Test: 6,992

In [4]:
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def tokenize_function(examples):
    return tokenizer(examples['text_input'], truncation=True, padding='max_length', max_length=MAX_LENGTH)

train_dataset = Dataset.from_pandas(train_df[['text_input', 'virality_score']])
val_dataset = Dataset.from_pandas(val_df[['text_input', 'virality_score']])
test_dataset = Dataset.from_pandas(test_df[['text_input', 'virality_score']])

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

train_dataset = train_dataset.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])
val_dataset = val_dataset.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])
test_dataset = test_dataset.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/32623 [00:00<?, ? examples/s]

Map:   0%|          | 0/6990 [00:00<?, ? examples/s]

Map:   0%|          | 0/6992 [00:00<?, ? examples/s]

Map:   0%|          | 0/32623 [00:00<?, ? examples/s]

Map:   0%|          | 0/6990 [00:00<?, ? examples/s]

Map:   0%|          | 0/6992 [00:00<?, ? examples/s]

In [5]:
model = AutoModelForSequenceClassification.from_pretrained(BASE_MODEL, num_labels=1, problem_type="regression")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    mae = mean_absolute_error(labels, predictions)
    rmse = np.sqrt(mean_squared_error(labels, predictions))
    r2 = r2_score(labels, predictions)
    return {'mae': mae, 'rmse': rmse, 'r2': r2}

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [6]:
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_dir = f"{OUTPUT_DIR}/{BASE_MODEL.replace('/', '_')}_{TASK}_{timestamp}"

training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="mae",
    greater_is_better=False,
    save_total_limit=2,
    seed=42,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()

TrainOutput(global_step=6117, training_loss=0.13528222341601398, metrics={'train_runtime': 741.6404, 'train_samples_per_second': 131.963, 'train_steps_per_second': 8.248, 'total_flos': 6482110318235136.0, 'train_loss': 0.13528222341601398, 'epoch': 3.0})

In [8]:
test_results = trainer.evaluate(test_dataset)
print("Test Results:")
for key, value in test_results.items():
    if 'eval_' in key:
        print(f"  {key}: {value:.4f}")

trainer.save_model()
tokenizer.save_pretrained(output_dir)

metadata = {
    'base_model': BASE_MODEL,
    'task': TASK,
    'test_results': {k: float(v) for k, v in test_results.items()},
    'timestamp': timestamp,
}

with open(f'{output_dir}/metadata.json', 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"Model saved to {output_dir}")

Test Results:
  eval_loss: 0.2174
  eval_mae: 0.2818
  eval_rmse: 0.4663
  eval_r2: 0.0800
  eval_runtime: 14.5459
  eval_samples_per_second: 480.6840
  eval_steps_per_second: 30.0430
Model saved to /content/models_foundation/distilbert-base-uncased_regression_20251229_205043

In [7]:
# Experiment 1: Try RoBERTa (better performance, slower)
BASE_MODEL_EXP1 = 'roberta-base'
BATCH_SIZE_EXP1 = 8  # Smaller batch for larger model

tokenizer_exp1 = AutoTokenizer.from_pretrained(BASE_MODEL_EXP1)
model_exp1 = AutoModelForSequenceClassification.from_pretrained(BASE_MODEL_EXP1, num_labels=1, problem_type="regression")

train_dataset_exp1 = Dataset.from_pandas(train_df[['text_input', 'virality_score']])
val_dataset_exp1 = Dataset.from_pandas(val_df[['text_input', 'virality_score']])
test_dataset_exp1 = Dataset.from_pandas(test_df[['text_input', 'virality_score']])

def tokenize_exp1(examples):
    return tokenizer_exp1(examples['text_input'], truncation=True, padding='max_length', max_length=MAX_LENGTH)

train_dataset_exp1 = train_dataset_exp1.map(tokenize_exp1, batched=True)
val_dataset_exp1 = val_dataset_exp1.map(tokenize_exp1, batched=True)
test_dataset_exp1 = test_dataset_exp1.map(tokenize_exp1, batched=True)

train_dataset_exp1 = train_dataset_exp1.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])
val_dataset_exp1 = val_dataset_exp1.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])
test_dataset_exp1 = test_dataset_exp1.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])

timestamp_exp1 = datetime.now().strftime("%Y%m%d_%H%M%S")
output_dir_exp1 = f"{OUTPUT_DIR}/{BASE_MODEL_EXP1.replace('/', '_')}_{TASK}_{timestamp_exp1}"

training_args_exp1 = TrainingArguments(
    output_dir=output_dir_exp1,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE_EXP1,
    per_device_eval_batch_size=BATCH_SIZE_EXP1,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="mae",
    greater_is_better=False,
    save_total_limit=2,
    seed=42,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

trainer_exp1 = Trainer(
    model=model_exp1,
    args=training_args_exp1,
    train_dataset=train_dataset_exp1,
    eval_dataset=val_dataset_exp1,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print(f"Training RoBERTa model...")
trainer_exp1.train()

test_results_exp1 = trainer_exp1.evaluate(test_dataset_exp1)
print("\nRoBERTa Test Results:")
for key, value in test_results_exp1.items():
    if 'eval_' in key:
        print(f"  {key}: {value:.4f}")

trainer_exp1.save_model()
tokenizer_exp1.save_pretrained(output_dir_exp1)
print(f"RoBERTa model saved to {output_dir_exp1}")

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/32623 [00:00<?, ? examples/s]

Map:   0%|          | 0/6990 [00:00<?, ? examples/s]

Map:   0%|          | 0/6992 [00:00<?, ? examples/s]

Map:   0%|          | 0/32623 [00:00<?, ? examples/s]

Map:   0%|          | 0/6990 [00:00<?, ? examples/s]

Map:   0%|          | 0/6992 [00:00<?, ? examples/s]

Training RoBERTa model...

RoBERTa Test Results:
  eval_loss: 0.2296
  eval_mae: 0.2789
  eval_rmse: 0.4792
  eval_r2: 0.0285
  eval_runtime: 26.1745
  eval_samples_per_second: 267.1300
  eval_steps_per_second: 33.3910
RoBERTa model saved to /content/models_foundation/roberta-base_regression_20251229_211242

In [9]:
# Experiment 2: Add metadata to text input
df_exp2 = df.copy()
df_exp2['text_input_enhanced'] = (
    df_exp2['text_hook'].astype(str) + " [SEP] " +
    df_exp2['caption'].astype(str) + " Category: " +
    df_exp2['main_category'].astype(str) + " Length: " +
    df_exp2['length'].astype(str) + "s"
)

train_df_exp2 = df_exp2.iloc[:train_size].copy()
val_df_exp2 = df_exp2.iloc[train_size:train_size+val_size].copy()
test_df_exp2 = df_exp2.iloc[train_size+val_size:].copy()

tokenizer_exp2 = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer_exp2.pad_token is None:
    tokenizer_exp2.pad_token = tokenizer_exp2.eos_token

def tokenize_exp2(examples):
    return tokenizer_exp2(examples['text_input_enhanced'], truncation=True, padding='max_length', max_length=MAX_LENGTH)

train_dataset_exp2 = Dataset.from_pandas(train_df_exp2[['text_input_enhanced', 'virality_score']])
val_dataset_exp2 = Dataset.from_pandas(val_df_exp2[['text_input_enhanced', 'virality_score']])
test_dataset_exp2 = Dataset.from_pandas(test_df_exp2[['text_input_enhanced', 'virality_score']])

train_dataset_exp2 = train_dataset_exp2.map(tokenize_exp2, batched=True)
val_dataset_exp2 = val_dataset_exp2.map(tokenize_exp2, batched=True)
test_dataset_exp2 = test_dataset_exp2.map(tokenize_exp2, batched=True)

train_dataset_exp2 = train_dataset_exp2.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])
val_dataset_exp2 = val_dataset_exp2.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])
test_dataset_exp2 = test_dataset_exp2.map(lambda x: {'labels': float(x['virality_score'])}, remove_columns=['virality_score'])

model_exp2 = AutoModelForSequenceClassification.from_pretrained(BASE_MODEL, num_labels=1, problem_type="regression")

timestamp_exp2 = datetime.now().strftime("%Y%m%d_%H%M%S")
output_dir_exp2 = f"{OUTPUT_DIR}/{BASE_MODEL.replace('/', '_')}_with_metadata_{TASK}_{timestamp_exp2}"

training_args_exp2 = TrainingArguments(
    output_dir=output_dir_exp2,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="mae",
    greater_is_better=False,
    save_total_limit=2,
    seed=42,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

trainer_exp2 = Trainer(
    model=model_exp2,
    args=training_args_exp2,
    train_dataset=train_dataset_exp2,
    eval_dataset=val_dataset_exp2,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print(f"Training DistilBERT with metadata...")
trainer_exp2.train()

test_results_exp2 = trainer_exp2.evaluate(test_dataset_exp2)
print("\nDistilBERT + Metadata Test Results:")
for key, value in test_results_exp2.items():
    if 'eval_' in key:
        print(f"  {key}: {value:.4f}")

trainer_exp2.save_model()
tokenizer_exp2.save_pretrained(output_dir_exp2)
print(f"Model with metadata saved to {output_dir_exp2}")

Map:   0%|          | 0/32623 [00:00<?, ? examples/s]

Map:   0%|          | 0/6990 [00:00<?, ? examples/s]

Map:   0%|          | 0/6992 [00:00<?, ? examples/s]

Map:   0%|          | 0/32623 [00:00<?, ? examples/s]

Map:   0%|          | 0/6990 [00:00<?, ? examples/s]

Map:   0%|          | 0/6992 [00:00<?, ? examples/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training DistilBERT with metadata...

DistilBERT + Metadata Test Results:
  eval_loss: 0.2079
  eval_mae: 0.2755
  eval_rmse: 0.4560
  eval_r2: 0.1204
  eval_runtime: 13.9228
  eval_samples_per_second: 502.1970
  eval_steps_per_second: 31.3870
Model with metadata saved to /content/models_foundation/distilbert-base-uncased_with_metadata_regression_20251229_214945

In [10]:
# Compare all results
print("="*80)
print("MODEL COMPARISON")
print("="*80)
print(f"\nBaseline (DistilBERT):")
print(f"  R²: {test_results.get('eval_r2', 0):.4f}")
print(f"  MAE: {test_results.get('eval_mae', 0):.4f}")

if 'test_results_exp1' in locals():
    print(f"\nRoBERTa:")
    print(f"  R²: {test_results_exp1.get('eval_r2', 0):.4f}")
    print(f"  MAE: {test_results_exp1.get('eval_mae', 0):.4f}")

if 'test_results_exp2' in locals():
    print(f"\nDistilBERT + Metadata:")
    print(f"  R²: {test_results_exp2.get('eval_r2', 0):.4f}")
    print(f"  MAE: {test_results_exp2.get('eval_mae', 0):.4f}")

print("="*80)

================================================================================
MODEL COMPARISON
================================================================================

Baseline (DistilBERT):
  R²: 0.0800
  MAE: 0.2818

RoBERTa:
  R²: 0.0285
  MAE: 0.2789

DistilBERT + Metadata:
  R²: 0.1204
  MAE: 0.2755
================================================================================

In [ ]:
from google.colab import files
import os

model_dir = "/content/models_foundation"
if os.path.exists(model_dir):
    model_folders = [os.path.join(model_dir, d) for d in os.listdir(model_dir)
                     if os.path.isdir(os.path.join(model_dir, d))]
    if model_folders:
        latest_model = max(model_folders, key=os.path.getmtime)
        for file in ['pytorch_model.bin', 'config.json', 'tokenizer_config.json', 'vocab.txt', 'metadata.json']:
            file_path = os.path.join(latest_model, file)
            if os.path.exists(file_path):
                files.download(file_path)